---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node2
spec:
  storageClassName: gp2-general
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: node2keys
data:
  key: MHgyOGIzMmRmNWNiYWJmZTUzMWQwMGE3ZDAxMmViODk2NTRkNjY0MzlmNjFlYTlkMTBlNzBkOTAwMzM0ZTFlNGVl
  key.pub: MHg3NjJmM2NlMzlmMGM4NzRiMDZiZTRkMDZhNDQ3N2M5MjgwYjhiMzg4NDVhNDQ0NDVhNzk5NDdjZjRhNjIyN2FiZWQ2NjYyMzA0MjQ4ZjgxMGQ2OGUzZWQyNzNmNTkzYmM2M2FhODJlNTc4ZTE4NTg2M2I1NzNmZTFiOTUzZjY1Ng==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: node2cfg
data:
  config.toml: |
    bootnodes=["enode://e016a78ebaf9ddf694e8ec618f469cdee35d53b736f1fa973b150093cffc7ec7d92fdd93a4c1737c028f8bd67f5a0ca28a75167191299e08156f3b43855616c1@node1dmlkh.{{DOMAIN}}:30303"]
    data-path="/etc/data"
    discovery-enabled=true
    genesis-file="/etc/config/genesis/genesis.json"
    host-allowlist=["*"]
    logging="DEBUG"
    max-peers=25
    node-private-key-file="/etc/keys/key"
    p2p-enabled=true
    p2p-host="0.0.0.0"
    p2p-port=30303
    revert-reason-enabled=true
    rpc-http-api=["DEBUG", "ETH", "WEB3", "NET", "TRACE", "QBFT", "TXPOOL", "ADMIN", "PERM", "EEA"]
    rpc-http-authentication-enabled=false
    rpc-http-cors-origins=["all"]
    rpc-http-enabled=true
    rpc-http-host="0.0.0.0"
    rpc-http-max-active-connections=80
    rpc-http-port=8545
    rpc-ws-api=["DEBUG", "ETH", "WEB3", "NET", "TRACE", "QBFT", "TXPOOL", "ADMIN", "PERM", "EEA"]
    rpc-ws-authentication-enabled=false
    rpc-ws-enabled=true
    rpc-ws-host="0.0.0.0"
    rpc-ws-max-active-connections=80
    rpc-ws-port=8546
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node2
spec:
  selector:
    matchLabels:
      node: node2
  template:
    metadata:
      labels:
        node: node2
    spec:
      volumes:
        - name: config
          configMap:
            name: node2cfg
        - name: genesis
          configMap:
            name: genesis
        - name: data
          persistentVolumeClaim:
            claimName: node2
        - name: keys
          secret:
            secretName: node2keys
      initContainers:
        - name: fix-perms
          image: busybox
          volumeMounts:
            - mountPath: /etc/data
              name: data
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
          securityContext:
            runAsUser: 0
          command:
            - sh
            - -c
            - chown -R 1000:1000 /etc/data
      containers:
        - name: main
          image: hyperledger/besu:24.3.0
          volumeMounts:
            - mountPath: /etc/config/genesis
              name: genesis
            - mountPath: /etc/config/node
              name: config
            - mountPath: /etc/keys
              name: keys
            - mountPath: /etc/data
              name: data
          ports:
            - containerPort: 30303
              protocol: UDP
            - containerPort: 8545
              protocol: TCP
            - containerPort: 8546
              protocol: TCP
          command:
            - /bin/bash
            - -c
            - --
          args:
            - /opt/besu/bin/besu --Xdns-enabled=true --Xdns-update-enabled=true --Xnat-kube-service-name=node2 --config-file=/etc/config/node/config.toml --min-gas-price=0
---
apiVersion: v1
kind: Service
metadata:
  name: node2
spec:
  selector:
    node: node2
  ports:
    - port: 30303
      targetPort: 30303
      name: p2p
    - port: 8545
      targetPort: 8545
      name: rpc
    - port: 8546
      targetPort: 8546
      name: rpcws
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteUDP
metadata:
  name: node2p2p
spec:
  routes:
    - kind: Rule
      match: Host(`node2.{{DOMAIN}}`)
      services:
        - name: node2
          port: 30303
